[package]
name = "worker"
version = "0.1.0"
authors = ["Jacob LeGrone <npm@jacob.work>"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3.5"

[dependencies.web-sys]
version = "0.3.6"
features = [
  'Worker',
  'DedicatedWorkerGlobalScope',
]

[dev-dependencies]
wasm-bindgen-test = "0.2"
